/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: example.i

package example

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _goslice_ swig_type_1;
typedef _goslice_ swig_type_2;
extern void _wrap_Swig_free_example_94bf2401246d4292(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_example_94bf2401246d4292(swig_intgo arg1);
extern void _wrap_add_example_94bf2401246d4292(swig_voidp arg1, swig_voidp arg2, swig_voidp arg3);
extern swig_voidp _wrap_new_intp_example_94bf2401246d4292(void);
extern swig_voidp _wrap_copy_intp_example_94bf2401246d4292(swig_intgo arg1);
extern void _wrap_delete_intp_example_94bf2401246d4292(swig_voidp arg1);
extern void _wrap_intp_assign_example_94bf2401246d4292(swig_voidp arg1, swig_intgo arg2);
extern swig_intgo _wrap_intp_value_example_94bf2401246d4292(swig_voidp arg1);
extern void _wrap_sub_example_94bf2401246d4292(swig_intgo arg1, swig_intgo arg2, swig_type_1 arg3);
extern swig_intgo _wrap_divide_example_94bf2401246d4292(swig_intgo arg1, swig_intgo arg2, swig_type_2 arg3);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_example_94bf2401246d4292(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_example_94bf2401246d4292(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Add(arg1 *int, arg2 *int, arg3 *int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_add_example_94bf2401246d4292(C.swig_voidp(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func New_intp() (_swig_ret *int) {
	var swig_r *int
	swig_r = (*int)(C._wrap_new_intp_example_94bf2401246d4292())
	return swig_r
}

func Copy_intp(arg1 int) (_swig_ret *int) {
	var swig_r *int
	_swig_i_0 := arg1
	swig_r = (*int)(C._wrap_copy_intp_example_94bf2401246d4292(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Delete_intp(arg1 *int) {
	_swig_i_0 := arg1
	C._wrap_delete_intp_example_94bf2401246d4292(C.swig_voidp(_swig_i_0))
}

func Intp_assign(arg1 *int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_intp_assign_example_94bf2401246d4292(C.swig_voidp(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Intp_value(arg1 *int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_intp_value_example_94bf2401246d4292(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func Sub(arg1 int, arg2 int, arg3 []int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_sub_example_94bf2401246d4292(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func Divide(arg1 int, arg2 int, arg3 []int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_divide_example_94bf2401246d4292(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}


